# Generated by Django 3.2 on 2022-12-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_filmwork_certificate_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.TextField(
                choices=[("male", "male"), ("female", "female")],
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
