# Generated by Django 3.2 on 2022-12-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_person_gender"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "content"."genre_film_work"
                ADD CONSTRAINT "genre_film_work_film_work_id_genre_id_uniq"
                UNIQUE ("film_work_id", "genre_id");
                ALTER TABLE "content"."person_film_work"
                ADD CONSTRAINT "person_film_work_film_work_id_person_id_role_uniq"
                UNIQUE ("film_work_id", "person_id", "role");
            """,
            reverse_sql="""
                ALTER TABLE "content"."genre_film_work"
                DROP CONSTRAINT genre_film_work_film_work_id_genre_id_uniq;
                ALTER TABLE "content"."genre_film_work"
                DROP CONSTRAINT person_film_work_film_work_id_person_id_role_uniq
            """,
        )
    ]
