# Generated by Django 3.2 on 2023-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_all_tables_created_updated_auto_now_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.TextField(
                choices=[
                    ("actor", "Actor"),
                    ("director", "Dicrector"),
                    ("writer", "Writer"),
                ],
                null=True,
                verbose_name="role",
            ),
        ),
    ]
